### ISSUE TITLE
Which files to manage?

### ISSUE THREAD

**Issue by martbhell** [mhakala/ansible-role-pam#4]
On my CentOS7 the relevant files in /etc/pam.d/ look like below.
- Why is this role not managing password-auth-ac but system-auth-ac?
- Wouldn't it be enough to only manage the -ac files?

system-auth:

```
lrwxrwxrwx. 1 root root  14 Jan 27 16:23 system-auth -> system-auth-ac
-rw-r--r--. 1 root root 974 Jan 27 16:23 system-auth-ac

```

password-auth:

```
lrwxrwxrwx. 1 root root  16 Jan 27 16:23 password-auth -> password-auth-ac
-rw-r--r--. 1 root root 974 Jan 27 16:23 password-auth-ac
```

**Comment by jabl** [comment]
See http://linux.die.net/man/5/system-auth-ac

tl;dr: When authconfig runs it generates the -ac files and creates the symlinks. pam itself uses only the non-ac paths. So it should be sufficient to just replace the non-ac symlinks with files and not touch the -ac files?

**Comment by jabl** [comment]
Implemented in https://github.com/jabl/ansible-role-pam/commit/ba4a9860d9f5f74ffede02e7d96a56fca0446302
